### ISSUE TITLE
Doorlock gates goes wrong somehow

### ISSUE THREAD

**Issue by Vampirepsc** [HumanTree92/FiveM_CustomMapAddons#2]
Hello there, thanks for the adding first 
And im facing a problem I copied the door cords you put in the Readme file,
But after that, the doorlock is completely useless (including all the original police offices doors),
the F8 console goes like
Error resuming coroutine: Invalid Lua type in __data
stack traceback:
[C]: in global '_in'
Get ClosestObjectOfType. lua:4: in function 'GetClosestObjectOfType'
@esx_doorlock/client/main.lua:40: in function <@esx_doorlock/client/main.lua:29>
Error resuming coroutine: @esx_doorlock/client/main.lua:60: attempt to perform arithmetic on a vector3 value (local 'playerCoords')
stack traceback:
@esx_doorlock/clinet/main.lua:60: in function <@esx_doorlock/client/main.lua:49>

Plz help 
thanks

**Comment by HumanTree92** [comment]
I will be uploading a new version of the Readme soon.
