### ISSUE TITLE
Paleto Bay sheriff place

### ISSUE THREAD

**Issue by iSentrie** [HumanTree92/FiveM_CustomMapAddons#3]
![image](https://user-images.githubusercontent.com/29688478/62207043-ca7cf380-b39b-11e9-8b07-dd30584d2d97.png)
Can you fix it or share .xml so I could pull request it.

**Comment by HumanTree92** [comment]
You must be using a different map files b/c my server doesn't have that.

**Comment by iSentrie** [comment]
Oh if so I will look in to it.

What about
![image](https://user-images.githubusercontent.com/29688478/62210657-547d8a00-b3a5-11e9-93dd-8e92f3587e0e.png)
Gate blocks the sign.

EDIT: disabled all maps, seems like these are spawned by default :x i would like to fix those for myself then, could you share .xml?
![image](https://user-images.githubusercontent.com/29688478/62211119-690e5200-b3a6-11e9-9e26-b16f631b6326.png)

EDIT2: also it looks different from your screenshots... using your .ymap of PB sherrifs place looks like
![image](https://user-images.githubusercontent.com/29688478/62211820-28afd380-b3a8-11e9-9193-9390809f75ed.png)
and in your screenshot its:
![image](https://user-images.githubusercontent.com/29688478/62211899-5a289f00-b3a8-11e9-9b74-7a6ff82d17f6.png)

**Comment by HumanTree92** [comment]
After a thorough search i have determined that the added props are not there by default.
